#app name
app:
  name: "ntn-accounts-sf-jde-sync-papi"  
  env: "PROD" 
http:
  host: "0.0.0.0"
  port: "8081"
  timeout: "15000"
  
jde.sapi:
  host: "ntn-accounts-sf-jde-sync-sapi-prod-xbmlkc.xryhvh.usa-e2.cloudhub.io"
  port: "443"
  path: "/api/accounts"

    
#Request Timeout config
http-request:
  timeout: "6000000"  
  
#For Each batch size details 
smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "donotreply@ntnusa.com,ntnmule@prowesssoft.com"
  