#%RAML 1.0 DataType
type: object
properties:
      advPriceAG:
        required: false
        type: string | nil
        example: "No"
      ntnAdvPrcGrp:
        type: string | nil
        example: "MRO-MRO Schedule Name"
      alphaName:
        type: string | nil
        example: "SUPERCALIFRAGILISTIC MOTION CANADA LLC"
      billingAddressType:
        type: string | nil
        example: "B-Bill To Only"
      billToNumber:
        type: string | nil
        example: "17150"
      customerServiceCoordinatorCode:
        type: string | nil
        example: "LA-Loren Almeda"
      customerPriceGroup40PC:
        type: string | nil
        example: "MRO-Advanced Pricing (Aftermarket)"
      custTypeCode:
        type: string | nil
        example: "IAD-Industrial Authorized Dist."
      dunsNumber:
        type: string | nil
        example: "342805522"
      fax:
        type: string | nil
        example: "(612)3770639"
      ntnGlobalMarket:
        type: string | nil
        example: "IAM-Industrial Aftermarket"
      id:
        type: string | nil
        example: "001f000000gAiEAO"
      jdeAddressNumber:
        type: string | nil
        example: "320657"
      nbcaMarket:
        type: string | nil
        example: "20-Automotive Aftermarket"
      ntnCustomerGroup:
        type: string | nil
        example: "NAT-Wajax Industrial Components LP"
      ntnMarketCode:
        type: string | nil
        example: "Y-GENERAL DISTRIBUTOR"
      parentNumber:
        type: string | nil
        example: "17,150"
      phone:
        type: string | nil
        example: "(763)5192100"
      region:
        type: string | nil
        example: "EAS-Eastern Region"
      ntnSalesRep:
        type: string | nil
        example: "A2C-Kelly Lusk"
      searchType:
        type: string | nil
        example: "C"
        required: false
      shippingStateCode:
        type: string | nil
        example: "MN"
      shippingCity:
        type: string | nil
        example: "Crystal Lake"
      shippingCountryCode:
        type: string | nil
        example: "US"
      shippingPostalCode:
        type: string | nil
        example: "55429"
      shippingStreet:
        type: string | nil
        example: "1600 Bishop Ct. Corporate Office Suite 207 Unit 1"
      status:
        type: string | nil
        example: ""
        required: false
      ntnCompanyName:
        type: string | nil
        example: "NBCC"
      mktRep:
        type: string | nil
        example: "1-George Smith"
      engineer:
        type: string | nil
        example: "A2O-John Doorman"
      type:
        type: string | nil
        example: "Customer"  
  
	   



