#%RAML 1.0 DataType
type : object
properties:
  account :
    type: object
    properties:
      ABAN8 ? :
        type: number
        example: 31922
      ABALKY ?:  
        type : string
        example : " "
      ABTAX ?:
        type : string
        example : " "
      ABALPH  ?: 
        type : string
        example : "HOLROYD, LESLIE"
      ABDC ?: 
        type : string
        example : "HOLROYDLESLIE"
      ABMCU ?: 
        type : string
        example : "3000"
      ABSIC ?: 
        type : string
        example : "NBCC"
      ABLNGP ?: 
        type : string
        example : "  "
      ABAT1  ? : 
        type : string
        example : "C"
      ABCM ?: 
        type : string 
        example :  "  "
      ABTAXC ? : 
        type : string
        example : "  "
      ABAT2 ? : 
        type : string
        example : "N"
      ABAT3 ? :
        type : string
        example : "N"
      ABAT4 ? : 
        type : string
        example : "N"
      ABAT5 ? : 
        type : string 
        example : "N"
      ABATP ? : 
        type : string
        example : "N"
      ABATR ? : 
        type : string
        example :  "Y"
      ABATPR ? : 
        type: string
        example  : "N"
      ABAB3 ? : 
        type: string
        example  : " "
      ABATE ? : 
        type: string
        example  : "Y"
      ABSBLI ? : 
        type: string
        example  :  " "
      ABEFTB ? : 
        type: number
        example  : 0
      ABAN81 ? : 
        type: number
        example  : 31922
      ABAN82 ?: 
        type: number
        example  : 31922
      ABAN83 ?: 
        type: number
        example  : 31922
      ABAN84 ? : 
        type: number
        example  : 31922
      ABAN86 ?: 
        type: number
        example  :  31922
      ABAN85 ?: 
        type: number
        example  : 31922
      ABAC01 ?: 
        type: string
        example  : "   "
      ABAC02 ?: 
        type: string
        example  : "   "
      ABAC03 ?: 
        type: string
        example  : "   "
      ABAC04 ?: 
        type: string
        example  : " A04  "
      ABAC05 ?: 
        type: string
        example  : "   "
      ABAC06 ?: 
        type: string
        example  : "   "
      ABAC07 ?: 
        type: string
        example  : "   "
      ABAC08 ?: 
        type: string
        example  : "   "
      ABAC09 ?: 
        type: string
        example  : "   "
      ABAC10 ?: 
        type: string
        example  : "NAT"
      ABAC11 ?: 
        type: string
        example  : "   "
      ABAC12 ?: 
        type: string
        example  : "   "
      ABAC13 ?: 
        type: string
        example  : "   "
      ABAC14 ?: 
        type: string
        example  : "   "
      ABAC15 ?: 
        type: string
        example  : "   "
      ABAC16 ?: 
        type: string
        example  : "   "
      ABAC17 ?: 
        type: string
        example  : "   "
      ABAC18 ? : 
        type: string
        example  : "   "
      ABAC19 ? : 
        type: string
        example  : "   "
      ABAC20 ? : 
        type: string
        example  : "   "
      ABAC21 ?: 
        type: string
        example  : "   "
      ABAC22 ?: 
        type: string
        example  : "   "
      ABAC23 ?: 
        type: string
        example  : "   "
      ABAC24 ?: 
        type: string
        example  : "   "
      ABAC25 ? : 
        type: string
        example  : "   "
      ABAC26 ?: 
        type: string
        example  : "   "
      ABAC27 ?: 
        type: string
        example  : "   "
      ABAC28 ? : 
        type: string
        example  : "   "
      ABAC29 ?: 
        type: string
        example  : "   "
      ABAC30 ?: 
        type: string
        example  : "   "
      ABGLBA ?: 
        type: string
        example  : "        "
      ABPTI ?: 
        type: number
        example  : 0
      ABPDI ? : 
        type: number
        example  : 0
      ABMSGA ?: 
        type: string
        example  : " "
      ABRMK ? : 
        type: string
        example  : ""
      ABTXCT ?: 
        type: string
        example  : ""
      ABTX2 ?:
        type: string
        example  : " "
      ABALP1 ?: 
        type: string
        example  : ""
      ABURCD ?: 
        type: string
        example  : "  "
      ABURDT ?: 
        type: number
        example  : 0
      ABURAT ?: 
        type: number
        example  : 0
      ABURAB ?: 
        type: number
        example  : 0
      ABURRF ?: 
        type: string
        example  : "               "
      ABUSER ?: 
        type: string
        example  : "ACAMAMA   "
      ABPID ? : 
        type: string
        example  : "EP04012   "
      ABUPMJ ?: 
        type: number
        example  : 120105
      ABJOBN ?: 
        type: string
        example  : "omcscabloq"
      ABUPMT ?: 
        type: number
        example  : 130620
      ABPRGF ?: 
        type: string
        example  : " "
      ABSCCLTP ?: 
        type: string
        example  : "  "
      ABTICKER ?: 
        type: string
        example  : "          "
      ABEXCHG ?: 
        type: string
        example  : "          "
      ABDUNS ?:
        type: string
        example  : "             "
      ABCLASS01 ?: 
        type: string
        example  : "   "
      ABCLASS02 ?: 
        type: string
        example  : "   "
      ABCLASS03 ?: 
        type: string
        example  : "   "
      ABCLASS04 ?: 
        type: string
        example  : "   "
      ABCLASS05 ?: 
        type: string
        example  : "   "
      ABNOE ? : 
        type: number
        example  : 0
      ABGROWTHR ? : 
        type: number
        example  : 0
      ABYEARSTAR ?: 
        type: string
        example  : "               "
      ABAEMPGP ?:
        type: string
        example  : "     "
      ABACTIN ?: 
        type: string
        example  : " "
      ABREVRNG ? : 
        type: string
        example  : "     "
      ABSYNCS ?: 
        type: number
        example  : 10
      ABPERRS ?: 
        type: number
        example  : 10
      ABCAAD ? : 
        type: number
  accountDetails :
    type: object
    properties:
        F03012 :
          type: array
          items :
            properties:
              AIAN8 ?: 
                type : number
                example : 1003
              AICRCD ?: 
                type : string
                example : "   "
              AIBADT ?: 
                type : string
                example : "X"
              AIACL ?: 
                type : number
                example : 0
              AICMGR ?: 
                type : string
                example : ""
              AICPGP ?: 
                type : string
                example : ""
              AIDAOJ ?: 
                type : number
                example : 116296
              AIDLC ?: 
                type : number
                example : 0
              AIDB ?: 
                type : string
                example : "   "
              AIARPY ?: 
                type : number
                example : 1003
              AIHOLD ?: 
                type : string
                example : "  "
              AITRAR ?: 
                type : string
                example : "   "
              AIINMG ?: 
                type : string
                example : "   "
              AIAC06 ?: 
                type : string
                example : "   "
              AIAC05 ?: 
                type : string
                example : "   "  
        F0111 :
          type: array
          items:
            properties:
              WWAN8 ?: 
                type : number
                example : 1001
              WWIDLN ?: 
                type : number
                example : 0
        F0115:
          type : array
          items:
            properties:
              WPAN8 ?: 
                type : number
                example : 31922
              WPAR1 ? :
                type : string
                example : " " 
              WPPH1 ?:
                type : string
                example : "800-526-4473"
              WPPHTP ? :
                 type : string
                 example : " "
        F01151 :
          type: array
          items:
            properties:
              EAAN8 ? : 
                type : number
                example : 31922
              EAEMAL ? : 
                type : string
                example : "kwilliams@ntkaxle.com "
              EAETP ? : 
                type : string
                example : "E   "
              EARCK7 ?: 
                type : number
                example : 1
              EAIDLN ?: 
                type : number
                example : 0
        F4780 :  
          type: array
          items:
            properties:
              AXDC ?: 
                type : string
                example : "test"
              AXAN8 ?: 
                type : number
                example : 31922
              AXXRTS ?: 
                type : string
                example : "SF"
              AXEXRA ?: 
                type : string
                example : ""
        F0116 :
          type: array
          items:
            properties:
              ALAN8 ?: 
                type : number
                example : 1001
              ALADD1 ?: 
                type : string
                example : "1600 EAST BISHOP COURT "
              ALADD2 ?: 
                type : string
                example : "      "
              ALADD3 ?: 
                type : string
                example : "       "
              ALADD4 ?: 
                type : string
                example : "        "
              ALCTY1 ?: 
                type : string
                example : "MT. PROSPECT             "
              ALADDS ?: 
                type : string
                example : "IL "
              ALADDZ ?: 
                type : string
                example : "60056 "
              ALCTR ?: 
                type : string
                example : "US "
              ALEFTB ?: 
                type : number
                example : 0    
        F0014 :
          type: array
          items:
            properties:
              PNPTC ? : 
                type : string
                example : "MF "
              PNPTD ?: 
                type : string
                example : "End of Month following Invoice"
        F57DOLCU:
          type: array
          items:
            properties:
              CUAC04 ? : 
                type : string
                example : "A04"
              CUDEPT ?: 
                type : string
                example : "X           "
              CUALPH3 ?: 
                type : string
                example : ""
              CUAC06 ? : 
                type : string
                example : "A06"
              CUAC36 ?: 
                type : string
                example : " "
              CUAC32 ? : 
                type : string
                example : " "
        F0005 :
          type: array
          items:
            properties:
              DRDL01 ?: 
                type : string
                example : "Finishing  "
              DRDL02 ?: 
                type : string
                example : "       "
              DRSY ?: 
                type : string
                example : "00  "
              DRRT ?: 
                type : string
                example : "02"
              DRKY ?: 
                type : string
                example : "FIN"
              

            